iot.solution.logviewer/Controllers/SettingController.cs
using component.services.logger.viewer.Models.SettingModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;

namespace component.services.logger.viewer.Controllers
{
    public class SettingController : Controller
    {
        public IConfiguration Configuration { get; }
        public SettingController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public string GetConnectionString(string environment)
        {
            return Configuration["ConnectionStrings:" + environment];
        }

        // GET: Setting
        public ActionResult Index()
        {
            SettingModel ConfigurationList = new SettingModel();
            ConfigurationList.ConnectionList = ((Common.ConnectionStringName[])Enum.GetValues(typeof(Common.ConnectionStringName))).Select(c => new SelectListItem() { Value = Convert.ToString((int)c), Text = c.ToString() }).ToList();

            if (ConfigurationList.ConStringId == 0)
            {
                ConfigurationList.ConStringId = 1;
            }
            string ConnString = Enum.GetName(typeof(Common.ConnectionStringName), ConfigurationList.ConStringId);

            using (SqlConnection conn = new SqlConnection(GetConnectionString(ConnString)))
            {
                SqlCommand cmd = new SqlCommand("GetComponentConfigurationSetting");
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter param = new SqlParameter();
                param.ParameterName = "@applicationCode";
                param.Value = "";
                cmd.Parameters.Add(param);

                cmd.Connection = conn;
                conn.Open();
                SqlDataAdapter MyDataAdapter = new SqlDataAdapter();
                MyDataAdapter.SelectCommand = cmd;
                DataSet oDataset = new DataSet();
                DataTable oDatatable = new DataTable();
                cmd.ExecuteNonQuery();
                MyDataAdapter.Fill(oDataset);
                oDatatable = oDataset.Tables[0];
                conn.Close();

                foreach (DataRow dr in oDatatable.Rows)
                {
                    Setting obj = new Setting();
                    obj.ComponentConfigId = dr["ComponentConfigId"].ToString();
                    obj.Debug = Convert.ToBoolean(Convert.ToString(dr["Debug"]));
                    obj.Error = Convert.ToBoolean(Convert.ToString(dr["Error"]));
                    obj.Fatal = Convert.ToBoolean(Convert.ToString(dr["Fatal"]));
                    obj.Info = Convert.ToBoolean(Convert.ToString(dr["Info"]));
                    obj.Warn = Convert.ToBoolean(Convert.ToString(dr["Warn"]));
                    obj.SubscribeDebug = Convert.ToBoolean(Convert.ToString(dr["SubscribeDebug"]));
                    obj.SubscribeError = Convert.ToBoolean(Convert.ToString(dr["SubscribeError"]));
                    obj.CronJobDebug = Convert.ToBoolean(Convert.ToString(dr["CronJobDebug"]));
                    obj.CronJobInfo = Convert.ToBoolean(Convert.ToString(dr["CronJobInfo"]));
                    obj.CronJobWarn = Convert.ToBoolean(Convert.ToString(dr["CronJobWarn"]));
                    obj.CronJobError = Convert.ToBoolean(Convert.ToString(dr["CronJobError"]));
                    obj.CronJobFatal = Convert.ToBoolean(Convert.ToString(dr["CronJobFatal"]));
                    obj.OmsLog = Convert.ToBoolean(dr["IsOmsLog"].ToString());
                    obj.Name = dr["KeyName"].ToString();
                    ConfigurationList.SettingList.Add(obj);
                }
            }

            ViewBag.Message = "";

            ConfigurationList.ApplicationList = GetApplicationList(ConfigurationList.ConStringId, string.Empty);
            ConfigurationList.ApplicationCode = "All";

            return View(ConfigurationList);
        }

        [HttpPost]
        public ActionResult BindSetting(SettingModel model)
        {
            SettingModel ConfigurationList = new SettingModel();
            ConfigurationList.ConnectionList = ((Common.ConnectionStringName[])Enum.GetValues(typeof(Common.ConnectionStringName))).Select(c => new SelectListItem() { Value = Convert.ToString((int)c), Text = c.ToString() }).ToList();
            ConfigurationList.ConStringId = model.ConStringId;

            string ConnString = Enum.GetName(typeof(Common.ConnectionStringName), model.ConStringId);

            using (SqlConnection conn = new SqlConnection(GetConnectionString(ConnString)))
            {
                SqlCommand cmd = new SqlCommand("GetComponentConfigurationSetting");
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter param = new SqlParameter();
                param.ParameterName = "@applicationCode";
                param.Value = model.ApplicationCode;
                cmd.Parameters.Add(param);

                cmd.Connection = conn;
                conn.Open();
                SqlDataAdapter MyDataAdapter = new SqlDataAdapter();
                MyDataAdapter.SelectCommand = cmd;
                DataSet oDataset = new DataSet();
                DataTable oDatatable = new DataTable();
                cmd.ExecuteNonQuery();
                MyDataAdapter.Fill(oDataset);
                oDatatable = oDataset.Tables[0];
                conn.Close();

                foreach (DataRow dr in oDatatable.Rows)
                {
                    Setting obj = new Setting();
                    obj.ComponentConfigId = dr["ComponentConfigId"].ToString();
                    obj.Debug = Convert.ToBoolean(Convert.ToString(dr["Debug"]));
                    obj.Error = Convert.ToBoolean(Convert.ToString(dr["Error"]));
                    obj.Fatal = Convert.ToBoolean(Convert.ToString(dr["Fatal"]));
                    obj.Info = Convert.ToBoolean(Convert.ToString(dr["Info"]));
                    obj.Warn = Convert.ToBoolean(Convert.ToString(dr["Warn"]));
                    obj.SubscribeDebug = Convert.ToBoolean(Convert.ToString(dr["SubscribeDebug"]));
                    obj.SubscribeError = Convert.ToBoolean(Convert.ToString(dr["SubscribeError"]));
                    obj.CronJobDebug = Convert.ToBoolean(Convert.ToString(dr["CronJobDebug"]));
                    obj.CronJobInfo = Convert.ToBoolean(Convert.ToString(dr["CronJobInfo"]));
                    obj.CronJobWarn = Convert.ToBoolean(Convert.ToString(dr["CronJobWarn"]));
                    obj.CronJobError = Convert.ToBoolean(Convert.ToString(dr["CronJobError"]));
                    obj.CronJobFatal = Convert.ToBoolean(Convert.ToString(dr["CronJobFatal"]));
                    obj.Name = dr["KeyName"].ToString();
                    ConfigurationList.SettingList.Add(obj);
                }
            }

            ViewBag.Message = "";

            ConfigurationList.ApplicationList = GetApplicationList(ConfigurationList.ConStringId, string.Empty);

            return View("Index", ConfigurationList);
        }

        [HttpPost]
        public ActionResult Index(SettingModel model)
        {
            SettingModel ConfigurationList = new SettingModel();


            string ConnString = Enum.GetName(typeof(Common.ConnectionStringName), model.ConStringId);

            using (SqlConnection conn = new SqlConnection(GetConnectionString(ConnString)))
            {
                SqlCommand cmd = new SqlCommand("GetComponentConfigurationSetting");
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter param = new SqlParameter();
                param.ParameterName = "@applicationCode";
                param.Value = string.Equals(model.ApplicationCode, "all", StringComparison.OrdinalIgnoreCase) ? "AllToUpdate" : model.ApplicationCode;
                cmd.Parameters.Add(param);

                cmd.Connection = conn;
                conn.Open();
                SqlDataAdapter MyDataAdapter = new SqlDataAdapter();
                MyDataAdapter.SelectCommand = cmd;
                DataSet oDataset = new DataSet();
                DataTable oDatatable = new DataTable();
                cmd.ExecuteNonQuery();
                MyDataAdapter.Fill(oDataset);
                oDatatable = oDataset.Tables[0];
                conn.Close();

                foreach (DataRow dr in oDatatable.Rows)
                {
                    Setting obj = new Setting();
                    obj.ComponentConfigId = dr["ComponentConfigId"].ToString();
                    obj.Debug = Convert.ToBoolean(dr["Debug"].ToString());
                    obj.Error = Convert.ToBoolean(dr["Error"].ToString());
                    obj.Fatal = Convert.ToBoolean(dr["Fatal"].ToString());
                    obj.Info = Convert.ToBoolean(dr["Info"].ToString());
                    obj.Warn = Convert.ToBoolean(dr["Warn"].ToString());
                    obj.SubscribeDebug = Convert.ToBoolean(dr["SubscribeDebug"].ToString());
                    obj.SubscribeError = Convert.ToBoolean(dr["SubscribeError"].ToString());
                    obj.CronJobDebug = Convert.ToBoolean(Convert.ToString(dr["CronJobDebug"]));
                    obj.CronJobInfo = Convert.ToBoolean(Convert.ToString(dr["CronJobInfo"]));
                    obj.CronJobWarn = Convert.ToBoolean(Convert.ToString(dr["CronJobWarn"]));
                    obj.CronJobError = Convert.ToBoolean(Convert.ToString(dr["CronJobError"]));
                    obj.CronJobFatal = Convert.ToBoolean(Convert.ToString(dr["CronJobFatal"]));
                    obj.Name = dr["KeyName"].ToString();
                    ConfigurationList.SettingList.Add(obj);
                }
            }

            var changedSetting = (from s in model.SettingList
                                  join cs in ConfigurationList.SettingList

iot.solution.logviewer/Views/Setting/Index.cshtml
@model component.services.logger.viewer.Models.SettingModel.SettingModel
@{
    ViewBag.Title = "Component Configuration Page";
}

<style>
    .heading {
        background-color: #ffd800;
        width: 100%;
    }

    h3 {
        padding: 10px;
    }

    .divSetting {
    }
</style>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


<div>
    @using (Html.BeginForm("BindSetting", "Setting", FormMethod.Post))
    {
    <div style="margin-top:10px;width:100%;">
        <span style="float:left;width:25%;margin-left:10px;">
            @Html.DropDownListFor(n => n.ConStringId, new SelectList(Model.ConnectionList, "Value", "Text"), new { id = "drpConnection", @class = "form-control" })
        </span>
        <span style="float:left;width:25%;margin-left:10px;">
            @Html.DropDownListFor(n => n.ApplicationCode, new SelectList(Model.ApplicationList, "Value", "Text"), new { id = "drpApplication", @class = "form-control" })
        </span>
        <span style="float:left;">
            <button type="submit" class="btn btn-primary">Search</button>
        </span>
    </div>
        <div style="clear:both;">

        </div>
    }

</div>

@using (Html.BeginForm("Index", "Setting", FormMethod.Post))
{
    <div class="heading">
        <h3> Component Configuration </h3>
    </div>
    <div class="divSetting">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Setting Name</th>
                    <th>debug </th>
                    <th>error</th>
                    <th>fatal</th>
                    <th>info</th>
                    <th>warn</th>
                    <th>subscribedebug</th>
                    <th>subscribeerror</th>
                    <th>cronjobdebug</th>
                    <th>cronjoberror</th>
                    <th>cronjobfatal</th>
                    <th>cronjobinfo</th>
                    <th>cronjobwarn</th>
                    <th>omslog</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int i = 0;
                    foreach (var item in Model.SettingList.ToList())
                    {
                <tr>
                    @Html.HiddenFor(m => m.SettingList[i].ComponentConfigId, new { @id = "id_" + i })
                    @Html.HiddenFor(m => m.SettingList[i].Name, new { @id = "Name_" + i })
                    <td>@item.Name</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].Debug, new { @id = "debug_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].Error, new { @id = "error_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].Fatal, new { @id = "fatal_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].Info, new { @id = "info_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].Warn, new { @id = "warn_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].SubscribeDebug, new { @id = "subscribedebug_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].SubscribeError, new { @id = "subscribeerror_" + i })</td>

                    <td>@Html.CheckBoxFor(m => m.SettingList[i].CronJobDebug, new { @id = "cronjobdebug_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].CronJobError, new { @id = "cronjoberror_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].CronJobFatal, new { @id = "cronjobfatal_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].CronJobInfo, new { @id = "cronjobinfo_" + i })</td>
                    <td>@Html.CheckBoxFor(m => m.SettingList[i].CronJobWarn, new { @id = "cronjobwarn_" + i })</td>

                    <td>@Html.CheckBoxFor(m => m.SettingList[i].OmsLog, new { @id = "omslog_" + i })</td>
                </tr>
                        i++;
                    }
                }
            </tbody>

        </table>
    </div>
    <span style="float:left;">
        @Html.HiddenFor(m => m.ConStringId)
        @Html.HiddenFor(m => m.ApplicationCode)
        <button type="submit" class="btn btn-primary">Save</button>
    </span>
}

<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js">
</script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js">
</script>
<script type="text/javascript">

    $(document).ready(function () {
        if ('@ViewBag.Message' != "") {
            toastr.success('@ViewBag.Message');
        }
    });


</script>